version: '2.1'

services:
  sosdb-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: sosdb-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sosdb
      MYSQL_USER: sosuser
      MYSQL_PASSWORD: sosuser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - sos-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=sosuser --password=sosuser --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 20
    volumes:
      - sosdb-n1-data:/var/lib/mysql

  sosdb-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: sosdb-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sosdb
      MYSQL_USER: sosuser
      MYSQL_PASSWORD: sosuser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - sos-network
    ports:
      - 3361:3306
    healthcheck:
      test: "/usr/bin/mysql --user=sosuser --password=sosuser --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 20
    volumes:
      - sosdb-n2-data:/var/lib/mysql

  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=sosuser --password=sosuser --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10
    networks:
      - sos-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
    depends_on:
      sosdb-node-1:
        condition: service_healthy
      sosdb-node-2:
        condition: service_healthy

  user_service:
    build:
      context: UserService
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=sosuser
      - DB_PASSWORD=sosuser
      - DB_DATABASE=sosdb
    ports:
      - 8080:8080
    networks:
      - sos-network
    depends_on:
      proxysql:
        condition: service_started

  service_service:
    build:
      context: ServiceService
      dockerfile: Dockerfile
    container_name: service_service
    restart: unless-stopped
    environment:
      - SERVICE_HOST=user_service
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=sosuser
      - DB_PASSWORD=sosuser
      - DB_DATABASE=sosdb
    ports:
      - 8081:8081
    networks:
      - sos-network
    depends_on:
      user_service:
        condition: service_started

  order_service:
    build:
      context: OrderService
      dockerfile: Dockerfile
    container_name: order_service
    restart: unless-stopped
    environment:
      - SERVICE_HOST=user_service
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=sosuser
      - DB_PASSWORD=sosuser
      - DB_DATABASE=sosdb
    ports:
      - 8082:8082
    networks:
      - sos-network
    depends_on:
      user_service:
        condition: service_started

volumes:
  sosdb-n1-data:
  sosdb-n2-data:
  proxysql-data:

networks:
  sos-network:
    driver: "bridge"
    external: false
